version = "0.1"

base {
    archivesName = "bbs-engine"
}

dependencies {
    /* Unit testing */
    testImplementation "org.junit.jupiter:junit-jupiter-api:5.3.1"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:5.3.1"
}

/* Utility tasks */

tasks.register("copyRuntimeLibs", Copy) {
    from sourceSets.main.compileClasspath
    into "build/dependencies/"
}

tasks.build.dependsOn.add(tasks.named("copyRuntimeLibs"))